#pragma once

// Data table for the user manual embedded at build time. Generated by
// cmake/gen_manual_assets.cmake from docs/user_manual.html and
// docs/screenshots/**; the symbols are defined in the generated
// user_manual_embedded.cpp.
//
// `path` is the forward-slash, URL-decoded path relative to docs/
// (e.g. "user_manual.html", "screenshots/ribbon menu/file.png"). `data`/`size`
// are the raw file bytes.
struct EmbeddedManualFile {
    const char* path;
    const unsigned char* data;
    unsigned int size;
};

extern const EmbeddedManualFile kUserManualFiles[];
extern const unsigned int kUserManualFileCount;
