// Generated by hitran/generate_gas_bands.py — do not edit
#pragma once
inline constexpr HitranBand kGasN2oBands[] = {
    { 550.0, 650.0 },
    { 1250.0, 1350.0 },
    { 2150.0, 2350.0 },
    { 3450.0, 3550.0 },
};
