// Generated by hitran/generate_gas_bands.py — do not edit
#pragma once
inline constexpr HitranBand kGasO3Bands[] = {
    { 50.0, 150.0 },
    { 650.0, 750.0 },
    { 950.0, 1150.0 },
    { 2050.0, 2150.0 },
};
