# gen_manual_assets.cmake — build-time generator that embeds the user manual
# (docs/user_manual.html + docs/screenshots/**) into a C++ translation unit.
#
# Invoked by CMakeLists.txt via `cmake -P`, with:
#   DOCS_DIR  absolute path of the docs/ directory
#   OUT_CPP   absolute path of the .cpp to generate
#
# xxd (already a build dependency — see the assets/icon.png embedding) emits the
# byte arrays. The output defines the symbols declared in
# io/user_manual_embedded.h. It is regenerated whenever the manual or any
# screenshot changes, so docs/user_manual.html stays the single maintained
# source.
#
# Paths are stored forward-slash and URL-decoded, relative to docs/. The manual
# references images as e.g. "screenshots/ribbon%20menu/file.png"; the browser
# percent-decodes that to the real on-disk name, so no HTML rewriting is needed.

if(NOT DEFINED DOCS_DIR OR NOT DEFINED OUT_CPP)
    message(FATAL_ERROR "gen_manual_assets.cmake requires -DDOCS_DIR and -DOUT_CPP")
endif()

find_program(XXD_EXECUTABLE xxd)
if(NOT XXD_EXECUTABLE)
    message(FATAL_ERROR "xxd not found — required to embed the user manual")
endif()

# The manual itself plus every screenshot (recursive, so new assets are picked
# up without editing this script).
set(entries "user_manual.html")
file(GLOB_RECURSE shot_abs RELATIVE "${DOCS_DIR}" LIST_DIRECTORIES false
     "${DOCS_DIR}/screenshots/*")
list(SORT shot_abs)
list(APPEND entries ${shot_abs})

get_filename_component(out_dir "${OUT_CPP}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")

set(body "// AUTO-GENERATED by cmake/gen_manual_assets.cmake — do not edit.\n")
string(APPEND body "// Embeds docs/user_manual.html and docs/screenshots/** into the binary.\n")
string(APPEND body "#include \"user_manual_embedded.h\"\n\n")
string(APPEND body "namespace {\n")

set(table "")
set(idx 0)
foreach(rel IN LISTS entries)
    set(sym "manual_asset_${idx}")
    set(in_path "${DOCS_DIR}/${rel}")
    set(tmp_h "${out_dir}/${sym}.h")
    execute_process(
        COMMAND "${XXD_EXECUTABLE}" -i -n "${sym}" "${in_path}"
        OUTPUT_FILE "${tmp_h}"
        RESULT_VARIABLE rc
    )
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR
            "xxd failed for ${in_path}.\n"
            "Embedding the user manual needs xxd from vim-common >= 8.2 "
            "(for the '-n' option). Install/upgrade it and reconfigure.")
    endif()
    file(READ "${tmp_h}" arr)
    string(APPEND body "\n${arr}")
    file(REMOVE "${tmp_h}")

    # Escape the relative path for use inside a C string literal.
    string(REPLACE "\\" "\\\\" rel_esc "${rel}")
    string(REPLACE "\"" "\\\"" rel_esc "${rel_esc}")
    string(APPEND table "    { \"${rel_esc}\", ${sym}, ${sym}_len },\n")
    math(EXPR idx "${idx} + 1")
endforeach()

string(APPEND body "} // namespace\n\n")
string(APPEND body "extern const EmbeddedManualFile kUserManualFiles[] = {\n${table}};\n")
string(APPEND body "extern const unsigned int kUserManualFileCount = ${idx};\n")
file(WRITE "${OUT_CPP}" "${body}")
